--------------------------------------------------------
--  颇老捞 积己凳 - 格夸老-2岿-02-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDERINFO
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ORDERINFO" 
   (	"ORDERNUMBER" NUMBER, 
	"PURCHASERID" NUMBER, 
	"ORDERDATE" DATE DEFAULT sysdate, 
	"PURCHASERSEQ" NUMBER, 
	"TOTALFEE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ORDERINFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."ORDERINFO_PK" ON "SCOTT"."ORDERINFO" ("ORDERNUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ORDERINFO
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ORDERINFO" ADD CONSTRAINT "ORDERINFO_PK" PRIMARY KEY ("ORDERNUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCOTT"."ORDERINFO" MODIFY ("ORDERNUMBER" NOT NULL ENABLE);
